[server]
debug_mode = true
addr = ':8088'

[log]
path = 'output/log'

[postgres]
dsn = "postgres://localhost:5432/wevote?sslmode=disable"

[redis]
addr = [':6377', ':6378']

[vote]
cache_ttl = '1h'
write_back_period = '1min'

[ticket]
secret = 'secret'
ttl = '2s'
usage_limit = 10000

[captcha]
open = false
recaptcha_secret = 'secret'
