[server]
debug_mode = true
addr = ':8088'

[log]
path = 'output/log'

[postgres]
host = 'localhost'
port = '5432'
user = 'postgres'
password = 'postgres'
dbname = 'wevote'

[redis]
addr = [':6377', ':6378']

[ticket]
secret = 'secret'
spec = 2            # seconds
upper_limit = 10000

[captcha]
recaptcha_secret = 'secret'
