[server]
debug_mode = true
addr = ':8088'

[log]
path = 'output/log'

[postgres]
dsn = "postgres://localhost:5432/wevote?sslmode=disable"

[redis]
addr = [':6377', ':6378']

[ticket]
secret = 'secret'
expiration = '2s'
upper_limit = 10000

[captcha]
recaptcha_secret = 'secret'
